=== roman-gulida/recipe-app/target/classes/xml/recipes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="recipeData">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="recipes" type="RecipesType"/>
                <xs:element name="users" type="UsersType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="RecipesType">
        <xs:sequence>
            <xs:element name="recipe" type="RecipeType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="RecipeType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="cuisine1" type="CuisineType"/>
            <xs:element name="cuisine2" type="CuisineType"/>
            <xs:element name="difficulty" type="DifficultyType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="UsersType">
        <xs:sequence>
            <xs:element name="user" type="UserType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="UserType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="surname" type="xs:string"/>
            <xs:element name="skillLevel" type="DifficultyType"/>
            <xs:element name="preferredCuisine" type="CuisineType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:simpleType name="DifficultyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Beginner"/>
            <xs:enumeration value="Intermediate"/>
            <xs:enumeration value="Advanced"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CuisineType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Italian"/>
            <xs:enumeration value="Asian"/>
            <xs:enumeration value="Mexican"/>
            <xs:enumeration value="French"/>
            <xs:enumeration value="British"/>
            <xs:enumeration value="Mediterranean"/>
            <xs:enumeration value="American"/>
            <xs:enumeration value="Indian"/>
            <xs:enumeration value="Middle Eastern"/>
            <xs:enumeration value="Japanese"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== roman-gulida/recipe-app/data/recipes.xml
<?xml version="1.0" encoding="UTF-8"?>
<recipeData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="recipes.xsd">

    <recipes>
        <recipe id="r001">
            <title>Pumpkin Soup with Crusty Bread</title>
            <cuisine1>British</cuisine1>
            <cuisine2>Mediterranean</cuisine2>
            <difficulty>Beginner</difficulty>
        </recipe>
        <recipe id="r002">
            <title>Beef and Root Vegetable Stew</title>
            <cuisine1>British</cuisine1>
            <cuisine2>French</cuisine2>
            <difficulty>Intermediate</difficulty>
        </recipe>
        <recipe id="r003">
            <title>Mushroom Risotto</title>
            <cuisine1>Italian</cuisine1>
            <cuisine2>Mediterranean</cuisine2>
            <difficulty>Intermediate</difficulty>
        </recipe>
        <recipe id="r004">
            <title>Spiced Butternut Squash Curry</title>
            <cuisine1>Indian</cuisine1>
            <cuisine2>Asian</cuisine2>
            <difficulty>Beginner</difficulty>
        </recipe>
        <recipe id="r005">
            <title>Sausage and Bean Casserole</title>
            <cuisine1>British</cuisine1>
            <cuisine2>American</cuisine2>
            <difficulty>Beginner</difficulty>
        </recipe>
        <recipe id="r006">
            <title>Slow-Cooked Lamb Shoulder</title>
            <cuisine1>Middle Eastern</cuisine1>
            <cuisine2>Mediterranean</cuisine2>
            <difficulty>Advanced</difficulty>
        </recipe>
        <recipe id="r007">
            <title>Chicken and Leek Pie</title>
            <cuisine1>British</cuisine1>
            <cuisine2>French</cuisine2>
            <difficulty>Intermediate</difficulty>
        </recipe>
        <recipe id="r008">
            <title>Pasta e Fagioli</title>
            <cuisine1>Italian</cuisine1>
            <cuisine2>Mediterranean</cuisine2>
            <difficulty>Beginner</difficulty>
        </recipe>
        <recipe id="r009">
            <title>Vegetable Tagine with Couscous</title>
            <cuisine1>Middle Eastern</cuisine1>
            <cuisine2>Mediterranean</cuisine2>
            <difficulty>Intermediate</difficulty>
        </recipe>
        <recipe id="r010">
            <title>Lentil Dahl with Naan</title>
            <cuisine1>Indian</cuisine1>
            <cuisine2>Asian</cuisine2>
            <difficulty>Beginner</difficulty>
        </recipe>
        <recipe id="r011">
            <title>Beef Bourguignon</title>
            <cuisine1>French</cuisine1>
            <cuisine2>Mediterranean</cuisine2>
            <difficulty>Advanced</difficulty>
        </recipe>
        <recipe id="r012">
            <title>Toad in the Hole</title>
            <cuisine1>British</cuisine1>
            <cuisine2>American</cuisine2>
            <difficulty>Beginner</difficulty>
        </recipe>
        <recipe id="r013">
            <title>Ramen Noodle Soup</title>
            <cuisine1>Japanese</cuisine1>
            <cuisine2>Asian</cuisine2>
            <difficulty>Intermediate</difficulty>
        </recipe>
        <recipe id="r014">
            <title>Chilli Con Carne</title>
            <cuisine1>Mexican</cuisine1>
            <cuisine2>American</cuisine2>
            <difficulty>Beginner</difficulty>
        </recipe>
        <recipe id="r015">
            <title>Roasted Root Vegetable Tart</title>
            <cuisine1>French</cuisine1>
            <cuisine2>British</cuisine2>
            <difficulty>Advanced</difficulty>
        </recipe>
        <recipe id="r016">
            <title>Pork and Apple Hotpot</title>
            <cuisine1>British</cuisine1>
            <cuisine2>French</cuisine2>
            <difficulty>Intermediate</difficulty>
        </recipe>
        <recipe id="r017">
            <title>Sweet Potato and Chickpea Stew</title>
            <cuisine1>Middle Eastern</cuisine1>
            <cuisine2>Indian</cuisine2>
            <difficulty>Beginner</difficulty>
        </recipe>
        <recipe id="r018">
            <title>Miso-Glazed Salmon</title>
            <cuisine1>Japanese</cuisine1>
            <cuisine2>Asian</cuisine2>
            <difficulty>Intermediate</difficulty>
        </recipe>
        <recipe id="r019">
            <title>Stuffed Bell Peppers with Rice</title>
            <cuisine1>Mediterranean</cuisine1>
            <cuisine2>Italian</cuisine2>
            <difficulty>Beginner</difficulty>
        </recipe>
        <recipe id="r020">
            <title>Duck Confit with Lentils</title>
            <cuisine1>French</cuisine1>
            <cuisine2>Mediterranean</cuisine2>
            <difficulty>Advanced</difficulty>
        </recipe>
        <recipe id="r021">
            <title>Black Bean Tacos</title>
            <cuisine1>Mexican</cuisine1>
            <cuisine2>American</cuisine2>
            <difficulty>Beginner</difficulty>
        </recipe>
        <recipe id="r022">
            <title>Chicken Tikka Masala</title>
            <cuisine1>Indian</cuisine1>
            <cuisine2>British</cuisine2>
            <difficulty>Intermediate</difficulty>
        </recipe>
    </recipes>

    <users>
        <user id="u001">
            <name>Jon</name>
            <surname>Jones</surname>
            <skillLevel>Intermediate</skillLevel>
            <preferredCuisine>Italian</preferredCuisine>
        </user>
    </users>

</recipeData>
